import { Header } from "@/components/Header/Header";
import "bootstrap/dist/css/bootstrap.css";
import "./global.css";
import { Footer } from "@/components/Footer/Footer";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
	name: "viewport",
	content: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
